version: '3'
name: margm

services:
  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    image: mysql:latest
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
          "-e",
          "SELECT 1"
        ]
      timeout: 20s
      retries: 10
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - .:/workspace:cached
      - data:/var/lib/mysql

  django-api:
    container_name: django-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
    links:
      - mysql-db
    ports:
      - "8000:8000"

volumes:
  data:
