version: '3.7'

services:
  django-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/workspace:cached
    command: python manage.py runserver localhost:8000
    links:
      - mysql-db

  mysql-db:
    image: mysql:lastest
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: MARGM_DB
      MYSQL_USER: developer
      MYSQL_PASSWORD: dev1234
    ports:
      - "3306:3306"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
