# Generated by Django 5.0.4 on 2024-04-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
