# Generated by Django 5.0.4 on 2024-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
