# Generated by Django 5.0.4 on 2024-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
