# Generated by Django 5.0.4 on 2024-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_livro', models.IntegerField()),
                ('texto', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
            ],
        ),
    ]
