# Generated by Django 5.0.4 on 2024-04-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_created_by'),
        ('resenhas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='cod_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro'),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
